New: Add aria-pressed to Icon Button
WTW-IM/es-components pull request #650
Opened 2022-09-21 15:03 UTC by darren-kuefner

2022-09-21 15:34 UTC, Darrken approved these changes

2022-09-26 15:43 UTC, stewartanderson3 approved these changes

2022-09-26 15:47 UTC, emmascanlon approved these changes

2022-09-27 22:05 UTC, g-gonzo requested changes
In QA Review

2022-10-11 16:02 UTC, stevematney requested changes
I believe the commit linter will fail because of the rough sentence casing in the commit. (@aabenoja is that right?)

```diff
- New: Add aria-pressed to Icon Button
+ New: add aria-pressed to Icon Button
```

2022-10-11 18:07 UTC, stevematney approved these changes

2022-10-12 16:32 UTC, merged