Allow Modal Header Size Alteration
WTW-IM/es-components pull request #808
Opened 2023-11-17 16:00 UTC by bradyclifford

Currently the size of the header cannot be changed.

2023-11-17 16:01 UTC, bradyclifford commented
I am sure I am missing some things in this PR.  For now this is just a proposal.

2024-01-18 22:00 UTC, stevematney requested changes
This change is fine, but I would like us to handle the prop types slightly differently.

Thank you!

2024-01-19 15:49 UTC, bradyclifford commented on packages/es-components/src/components/containers/modal/ModalHeader.tsx
> +import { HeadingLevel, HeadingSize } from 'es-components-shared-types';
This PR was just a pseudo example of what we wanted.

2024-01-19 16:01 UTC, bradyclifford commented on packages/es-components/src/components/containers/modal/ModalHeader.tsx
> +import { HeadingLevel, HeadingSize } from 'es-components-shared-types';
> "es-components-shared-types"' has no exported member named 'headingLevel'. Did you mean 'HeadingLevel'?

I will probably just have to pull this down to my local box and compile it.  Up until this point, I was only using the GitHub UI.

2024-01-19 16:02 UTC, bradyclifford commented
Any idea why the Cypress tests are failing?  Its failing on components this PR does not even touch.

2024-01-19 16:10 UTC, bradyclifford commented
> ## Commitlint
> ![commitlint results](https://camo.githubusercontent.com/d40d4a936e45b5c0006aa74a99b2b4c66cd6f22c7388444dcaeb7e31e3715030/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f31253246362d436f6d6d69746c696e742d726564)
> 
> The following commit messages do not meet our commit convention. Please reword these commits for correct versioning and changelog generation.
> 
> * Allow Modal Header Size Alteration
>   
>   * subject may not be empty
>   * type may not be empty
> * Update packages/es-components/src/components/containers/modal/ModalHeader.tsx
> 
> Co-authored-by: Steve Matney [steve.matney@extendhealth.com](mailto:steve.matney@extendhealth.com) * subject may not be empty * type may not be empty
> 
> * Update packages/es-components/src/components/containers/modal/ModalHeader.tsx
> 
> Co-authored-by: Steve Matney [steve.matney@extendhealth.com](mailto:steve.matney@extendhealth.com) * subject may not be empty * type may not be empty
> 
> * Update packages/es-components/src/components/containers/modal/ModalHeader.tsx
> 
> Co-authored-by: Steve Matney [steve.matney@extendhealth.com](mailto:steve.matney@extendhealth.com) * subject may not be empty * type may not be empty
> 
> * New: Allow modal header level alteration
>   
>   * subject must not be sentence-case, start-case, pascal-case, upper-case

Every commit has to have that format?

2024-01-24 16:24 UTC, stevematney commented
> Every commit has to have that format?
@bradyclifford yes.

2024-01-24 16:52 UTC, stevematney commented
> Any idea why the Cypress tests are failing? Its failing on components this PR does not even touch.

It's failing because `HeadingLevel` is only a type and not a js variable. That's why I recommended [this change](https://github.com/WTW-IM/es-components/pull/808#discussion_r1458017298).

https://github.com/WTW-IM/es-components/blob/cf2556f5b045f10043a5bb23e9e54250ebbe2573/shared/types/src/ESTheme.ts#L206

2024-01-24 20:17 UTC, bradyclifford commented
> > Any idea why the Cypress tests are failing? Its failing on components this PR does not even touch.
> 
> It's failing because `HeadingLevel` is only a type and not a js variable, so it can't build. That's why I recommended [this change](https://github.com/WTW-IM/es-components/pull/808#discussion_r1458017298).
> 
> https://github.com/WTW-IM/es-components/blob/cf2556f5b045f10043a5bb23e9e54250ebbe2573/shared/types/src/ESTheme.ts#L206

Oh ya that makes sense.  I must of missed that.  What I get for trying to make these adjustments from GitHub itself.

2024-01-26 16:49 UTC, stevematney approved these changes

2024-01-26 16:53 UTC, merged